[Rainmeter]
Update=16
BackgroundMode=2
SolidColor=0,0,0,1
DynamicWindowSize=1
AccurateText=1

[Metadata]
Name=GreatPanel
Author=neecride

; ---------- VARIABLES ----------
[Variables]
@IncludeVariables=#@#variables.inc

; ---------- AFFICHAGE ----------
; --- Arrière-plan ---
[MeterBackground]
Meter=Image
ImageName=#@#/Images/bg[#BackgroundChoice].png
W=334
H=620

; --- Avatar ---
[MeterAvatar]
Meter=Image
ImageName=#@#/Images/avatar/ava[#ChooseAvatar].png
X=35
Y=33
W=85
H=85

[MeterMaskCal]
Meter=Image
ImageName=#@#/Images/maskcal/MaskCal[#MaskCal].png
X=0
Y=454
W=334
H=166
SolidColor=255,255,255,0

; ---------- MESURES ----------

;--- includes ---
@Includes3=#@#Hdd.inc
@Includes4=#@#player.inc

[MeterSettinIcon]
Meter=Image
ImageName=#@#/Images/setting-lines.png
X=67
Y=200
W=15
H=15
ImageTint=179,179,179,255
UpdateDivider=-1
LeftMouseUpAction=!ToggleConfig "GreatPanel\Settings" "Settings.ini"

; --- Texte : Bonjour ---
[MeterHello]
Meter=String
Text="Hello %USERNAME%"
StringAlign=left
FontFace=Old Rocket
FontSize=18
FontColor=179,179,179,255
X=15
Y=150
AntiAlias=1

; --- Date ---
[MeasureDay]
Measure=Time
Format=%A
Substitute="Sunday":"Dimanche","Monday":"Lundi","Tuesday":"Mardi","Wednesday":"Mercredi","Thursday":"Jeudi","Friday":"Vendredi","Saturday":"Samedi"

; --- Date/Heure ---
[MeasureTime]
Measure=Time
Format=%H:%M

[MeasureDate]
Measure=Time
Format=%d

[MeasurePrevDay1]
Measure=Time
Format=%d
TimeStamp=([MeasureTime:Timestamp]-172800)

[MeasurePrevDay2]
Measure=Time
Format=%d
TimeStamp=([MeasureTime:Timestamp]-86400)

[MeasureNextDay1]
Measure=Time
Format=%d
TimeStamp=([MeasureTime:Timestamp]+86400)

[MeasureNextDay2]
Measure=Time
Format=%d
TimeStamp=([MeasureTime:Timestamp]+172800)

; --- Heure ---
[MeterHour]
Meter=String
MeasureName=MeasureTime
FontFace=#font#
FontSize=50
FontColor=46,50,97,255
X=252
Y=80
StringAlign=center
AntiAlias=1

[MeterDay]
Meter=String
MeasureName=MeasureDay
FontFace=Old Rocket
FontSize=26
FontColor=179,179,179,255
X=164
Y=415
StringAlign=Center
AntiAlias=1
Text="%1"

[MeterActualDays]
Meter=String
Text="[MeasureDate]"
FontFace=#font#
FontSize=50
FontColor=179,179,179,255
X=165
Y=15R
StringAlign=Center
AntiAlias=1

[MeterPrevDays1]
Meter=String
Text="[MeasurePrevDay1]"
FontFace=#font#
FontSize=20
FontColor=179,179,179,255
X=30
Y=500
StringAlign=Left
AntiAlias=1

[MeterPrevDays2]
Meter=String
Text="[MeasurePrevDay2]"
FontFace=#font#
FontSize=20
FontColor=179,179,179,255
X=86
Y=0r
StringAlign=Left
AntiAlias=1

[MeterNextDays1]
Meter=String
Text="[MeasureNextDay1]"
FontFace=#font#
FontSize=20
FontColor=179,179,179,255
X=226
Y=0r
StringAlign=Left
AntiAlias=1

[MeterNextDays2]
Meter=String
Text="[MeasureNextDay2]"
FontFace=#font#
FontSize=20
FontColor=179,179,179,255
X=282
Y=0r
StringAlign=Left
AntiAlias=1
