[Rainmeter]
Update=-1

[Metadata]
Name=GreatPanel
Author=neecride

[Variables]
@include=#@#variables.inc

[MeterBackground]
Meter=Image
ImageName=#@#/Images/bgSet.png
W=278
ImageTint=15, 15, 15

; ----------------------------------
; STYLES
; ----------------------------------

[styleTitle]
StringAlign=CENTER
StringCase=UPPER
StringStyle=NORMAL
StringEffect=SHADOW
FontEffectColor=0,0,0,50
FontColor=255,255,255
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleLeftText]
StringAlign=LEFT
StringCase=NONE
StringStyle=NORMAL
StringEffect=SHADOW
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

; ----------------------------------
; TITLE
; ----------------------------------

[meterTitle]
Meter=STRING
MeterStyle=styleTitle
X=140
Y=0
H=18
;Padding=#Padding#
Text="⬇ Choose Player ⬇"
SolidColor=46,50,97,255

;--- close btn --
[MeterCloseButton]
Meter=Image
ImageName=#@#Images\close.png
X=115r
Y=r
W=20
H=20
MouseOverAction=[!SetOption MeterCloseButton][!Update]
MouseLeaveAction=[!SetOption MeterCloseButton][!Update]
LeftMouseUpAction=[!DeactivateConfig "GreatPanel\Settings" "Settings.ini"]
DynamicVariables=1

; ----------------------------------
; PLAYER BUTTONS (Single Meter Version)
; ----------------------------------

[MeteriTunesButton]
Meter=image
X=22
Y=30
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/player/itunes.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeteriTunesButton SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeteriTunesButton SolidColor "255,255,255,30"][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables PlayerName iTunes "#@#variables.inc"][!Refresh *]

[MeterWMPButton]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/player/wmp.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterWMPButton SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterWMPButton SolidColor "255,255,255,30"][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables PlayerName WMP "#@#variables.inc"][!Refresh *]

[MeterSpotifyButton]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/player/spotify.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterSpotifyButton SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterSpotifyButton SolidColor "255,255,255,30"][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables PlayerName Spotify "#@#variables.inc"][!Refresh *]


;=== Boutons de avatar ===
[MeterChooseLang]
Meter=String
MeterStyle=styleLeftText
X=22
Y=80
W=230
H=18
Text="Choose Language  ⬇"
SolidColor=46,50,97,255


;=== Boutons de sélection ===
[MeterFRButton]
Meter=image
X=22
Y=10R
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/country/fr.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterFRButton SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterFRButton SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables lang "Fr" "#@#variables.inc"][!Refresh]

[MeterENButton]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/country/en.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterENButton SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterENButton SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables lang "En" "#@#variables.inc"][!Refresh]

[MeterESButton]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/country/es.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterESButton SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterESButton SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables lang "Es" "#@#variables.inc"][!Refresh]

;=== Boutons de background ===
[MeterChooseBg]
Meter=String
MeterStyle=styleLeftText
X=22
Y=10R
W=230
H=18
Text="Choose Calendar ⬇"
SolidColor=46,50,97,255

;=== Boutons de sélection ===
[MeterMaskCal0]
Meter=image
X=22
Y=10R
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/bgicon/mask0.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterMaskCal0 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterMaskCal0 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables MaskCal "0" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\mask0.png"][!UpdateMeter Background][!Refresh *]

[MeterMaskCal1]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/bgicon/mask1.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterMaskCal1 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterMaskCal1 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables MaskCal "1" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\mask1.png"][!UpdateMeter Background][!Refresh *]

[MeterMaskCal2]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/bgicon/mask2.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterMaskCal2 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterMaskCal2 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables MaskCal "2" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\mask2.png"][!UpdateMeter Background][!Refresh *]

[MeterMaskCal3]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/bgicon/mask3.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterMaskCal3 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterMaskCal3 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables MaskCal "3" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\mask3.png"][!UpdateMeter Background][!Refresh *]

[MeterMaskCal4]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/bgicon/mask4.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterMaskCal4 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterMaskCal4 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables MaskCal "4" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\mask4.png"][!UpdateMeter Background][!Refresh *]

[MeterMaskCal5]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/bgicon/mask5.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterMaskCal5 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterMaskCal5 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables MaskCal "5" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\mask5.png"][!UpdateMeter Background][!Refresh *]

;=== Boutons de background ===
[MeterChooseAvatar]
Meter=String
MeterStyle=styleLeftText
X=22
Y=10R
W=230
H=18
Text="Choose Avatar ⬇"
SolidColor=46,50,97,255

;=== Boutons de sélection ===
[MeterChooseAva0]
Meter=image
X=22
Y=10R
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/avatar/ava0.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterChooseAva0 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterChooseAva0 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables ChooseAvatar "0" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\avatar\ava0.png"][!UpdateMeter Background][!Refresh *]

[MeterChooseAva1]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/avatar/ava1.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterChooseAva1 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterChooseAva1 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables ChooseAvatar "1" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\avatar\ava1.png"][!UpdateMeter Background][!Refresh *]

[MeterChooseAva2]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/avatar/ava2.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterChooseAva2 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterChooseAva2 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables ChooseAvatar "2" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\avatar\ava2.png"][!UpdateMeter Background][!Refresh *]

[MeterChooseAva3]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/avatar/ava3.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterChooseAva3 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterChooseAva3 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables ChooseAvatar "3" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\avatar\ava3.png"][!UpdateMeter Background][!Refresh *]

[MeterChooseAva4]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/avatar/ava4.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterChooseAva4 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterChooseAva4 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables ChooseAvatar "4" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\avatar\ava4.png"][!UpdateMeter Background][!Refresh *]

[MeterChooseAva5]
Meter=image
X=39r
Y=r
W=30
H=30
Padding=#Padding#
ImageName=#@#/Images/avatar/ava5.png
SolidColor=255,255,255,30
MouseOverAction=[!SetOption MeterChooseAva5 SolidColor "18,160,230"][!Update]
MouseLeaveAction=[!SetOption MeterChooseAva5 SolidColor "255,255,255,30"][!Update]
LeftMouseUpAction=[!WriteKeyValue Variables ChooseAvatar "5" "#@#variables.inc"][!SetOption Background ImageName "#@#Images\avatar\ava5.png"][!UpdateMeter Background][!Refresh *]
